version: '3.3'

services:
  actloc_challenge:
    network_mode: host
    runtime: nvidia
    environment:
    - DISPLAY=$DISPLAY
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all
    - QT_X11_NO_MITSHM=1
    - XAUTHORITY=/tmp/.docker.xauth
    # - SSH_AUTH_SOCK=/ssh-agent
    volumes:
    - '/tmp/.X11-unix:/tmp/.X11-unix:rw'
    # - ${SSH_AUTH_SOCK}:/ssh-agent
    - '/tmp/.docker.xauth:/tmp/.docker.xauth'
    - '/home/boysun/actloc_benchmark/:/actloc_benchmark/'
    - '/mnt/hdd/actloc_example_data/example_data:/example_data'
    devices:
    - /dev/dri
    privileged: true
    image: boysun045/actloc_challenge:v1
    # command:  bash -c "ls"

